name: Create Release

on:
  push:
    branches:
      - main  # ou 'master', dependendo do nome da sua branch principal
    # Isso aciona o workflow se o commit for um 'vX.Y.Z'
    # Ajuste se quiser um padrão diferente
    paths-ignore:
      - '**/README.md'

jobs:
  create_release:
    if: startsWith(github.event.head_commit.message, 'v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from commit message
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}"

      - name: Check if release already exists
        id: check_release
        run: |
          if gh release view "${{ steps.get_version.outputs.VERSION }}" &>/dev/null; then
            echo "Release already exists!"
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: steps.check_release.outputs.exists == 'false'
        run: |
          gh release create "${{ steps.get_version.outputs.VERSION }}" --title "${{ steps.get_version.outputs.VERSION }}" --notes "Release created automatically."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
